### ISSUE TITLE
feat: monorepo support

### ISSUE THREAD

**Issue by privatenumber** [pkg-size/action#42]
## Is your feature request related to a problem? Please describe.

Support for monorepos.

**Comment by maxisam** [comment]
Is there a way to set the working directory? It seems like this only work if your project is at the root level

**Comment by maxisam** [comment]
It would be more useful if we have two new inputs like 

```yml
  working-directory: 
    description: where the build should run  
  dist-directory:
    description: where the dist folder is
```
and change the process cwd
`process.chdir(workingDirectory);`

also change this `await exec('pkg-size --json', { cwd: distDirectory })`
