### ISSUE TITLE
Include package path as option

### ISSUE THREAD

**Issue by miqdadfwz** [pkg-size/action#48]
## Is your feature request related to a problem? Please describe.

In monorepo scenario, It would be great if there is package path option so the action will not run against the whole packages

## Describe the solution you'd like

```
name: Package size report
        uses: pkg-size/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: path/to/package
```
